### ISSUE TITLE
Fan control issue

### ISSUE THREAD

**Issue by HalLandry** [ymerj/HE-HA-control#94]
Fan Control, componentSetSpeed turns the device off, but will not turn it on.

I adjusted line 700 from

if (speed == "off") executeCommand(ch, "turn_off"); return

to

    if (speed == "off") 
    {
        executeCommand(ch, "turn_off") 
        return
    }

This appears to correct the problem in a local copy of the driver

Hal

**Comment by ymerj** [comment]
Yes I forgot the darn brackets. Thanks
